SRC_DIR = srcs
HEADER_DIR = includes
CC = gcc
CFLAGS = -Wall -Wextra -Werror
CFILES = ft_putchar.c ft_swap.c ft_putstr.c ft_strlen.c ft_strcmp.c

# Remove object files
clean
# Remove the executable too
fclean
# make is equivalent to make all
make
# bien sur libft.a
make all
# make fclean + make all
re
